services:
  - type: web
    name: grewords-backend
    env: docker
    plan: free
    repo: https://github.com/shettyshreyas/grewordsapp  
    branch: main
    rootDir: backend
    envVars:
      - key: FLASK_ENV
        value: production
      - key: FLASK_APP
        value: app.py
      - fromDatabase:
          name: grewords-db
          property: connectionString
          key: DATABASE_URL

databases:
  - name: grewords-db
    databaseName: grewords
    user: grewordsuser
    plan: free