services:
  - type: web
    name: grewords-backend
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: grewords-db
          property: connectionString
      - key: PORT
        value: 5000
      - key: NODE_ENV
        value: production
    healthCheckPath: /api/health
    autoDeploy: true
    plan: free

databases:
  - name: grewords-db
    databaseName: grewords
    user: grewords
    plan: free 