"""Add TestSession model and update Word model

Revision ID: 89bfae6477c9
Revises: 
Create Date: 2025-04-02 15:26:49.306358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89bfae6477c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_progress', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_session_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_word_progress_test_session', 'test_session', ['test_session_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_progress', schema=None) as batch_op:
        batch_op.drop_constraint('fk_word_progress_test_session', type_='foreignkey')
        batch_op.drop_column('test_session_id')

    # ### end Alembic commands ###
